server:
  servlet:
    context-path: /railway-12306-transfer

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    password:

thread:
  sleep:
    wait: 3500
    click: 500
